//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eggsoft.Common.SR_DownLoad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_DownLoad.DownLoadServiceSoap")]
    public interface DownLoadServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Eggsoft.Common.SR_DownLoad.HelloWorldResponse HelloWorld(Eggsoft.Common.SR_DownLoad.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 address 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadFile", ReplyAction="*")]
        Eggsoft.Common.SR_DownLoad.DownLoadFileResponse DownLoadFile(Eggsoft.Common.SR_DownLoad.DownLoadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Eggsoft.Common.SR_DownLoad.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Eggsoft.Common.SR_DownLoad.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Eggsoft.Common.SR_DownLoad.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Eggsoft.Common.SR_DownLoad.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFile", Namespace="http://tempuri.org/", Order=0)]
        public Eggsoft.Common.SR_DownLoad.DownLoadFileRequestBody Body;
        
        public DownLoadFileRequest() {
        }
        
        public DownLoadFileRequest(Eggsoft.Common.SR_DownLoad.DownLoadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        public DownLoadFileRequestBody() {
        }
        
        public DownLoadFileRequestBody(string address, string filename) {
            this.address = address;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Eggsoft.Common.SR_DownLoad.DownLoadFileResponseBody Body;
        
        public DownLoadFileResponse() {
        }
        
        public DownLoadFileResponse(Eggsoft.Common.SR_DownLoad.DownLoadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DownLoadFileResponseBody {
        
        public DownLoadFileResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DownLoadServiceSoapChannel : Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownLoadServiceSoapClient : System.ServiceModel.ClientBase<Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap>, Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap {
        
        public DownLoadServiceSoapClient() {
        }
        
        public DownLoadServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownLoadServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownLoadServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownLoadServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eggsoft.Common.SR_DownLoad.HelloWorldResponse Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap.HelloWorld(Eggsoft.Common.SR_DownLoad.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Eggsoft.Common.SR_DownLoad.HelloWorldRequest inValue = new Eggsoft.Common.SR_DownLoad.HelloWorldRequest();
            inValue.Body = new Eggsoft.Common.SR_DownLoad.HelloWorldRequestBody();
            Eggsoft.Common.SR_DownLoad.HelloWorldResponse retVal = ((Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Eggsoft.Common.SR_DownLoad.DownLoadFileResponse Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap.DownLoadFile(Eggsoft.Common.SR_DownLoad.DownLoadFileRequest request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public void DownLoadFile(string address, string filename) {
            Eggsoft.Common.SR_DownLoad.DownLoadFileRequest inValue = new Eggsoft.Common.SR_DownLoad.DownLoadFileRequest();
            inValue.Body = new Eggsoft.Common.SR_DownLoad.DownLoadFileRequestBody();
            inValue.Body.address = address;
            inValue.Body.filename = filename;
            Eggsoft.Common.SR_DownLoad.DownLoadFileResponse retVal = ((Eggsoft.Common.SR_DownLoad.DownLoadServiceSoap)(this)).DownLoadFile(inValue);
        }
    }
}
